### ISSUE TITLE
Blender render missing file

### ISSUE THREAD

**Issue by chenzhike110** [nghorbani/soma#18]
when using render_mosh_once to visualize pkl. file generated by mosh, the soma_standard.blend is missing. could you share this file for us? What is the body in the blend file?

**Comment by chenzhike110** [comment]
sorry, i found the code

**Comment by ritaank** [comment]
where did you find it? I am able to get individual blend files for each frame, which get saved alongside the pngs. Is there a way to generate a blend file of the whole animation?

**Comment by wjrzm** [comment]
> sorry, i found the code

I want to know how to obtain this file? Could you please help me?

**Comment by wjrzm** [comment]
> where did you find it? I am able to get individual blend files for each frame, which get saved alongside the pngs. Is there a way to generate a blend file of the whole animation?

https://download.is.tue.mpg.de/download.php?domain=soma&sfile=blender/blend_files.tar.bz2
This link will help you download the `soma_standard.blend` file.
