### ISSUE TITLE
Cannot import name 'rm_spaces' from 'human_body_prior.tools.omni_tools'

### ISSUE THREAD

**Issue by Chen3110** [nghorbani/soma#3]
Hello! 
Thanks for your great work, it helps me a lot. Unfortunately, I meet some trouble when I run the code of SOMA on MoCap point cloud data. I cannot import 'rm_spaces' from 'human_body_prior.tools.omni_tools'. I found that there is no 'rm_spaces' function in 'human_body_prior.tools.omni_tools' module. Is there any new edition of 'human_body_prior' that I didn't find? 
Thank you very much!
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/53890856/152624571-b04551d1-abf6-4de0-9877-18154a3dd2e3.png">
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/53890856/152624707-b346bb4a-98e5-4443-ba5b-b4b0f2dab791.png">

**Comment by nghorbani** [comment]
are you using the SOMA branch of human_body_prior? i.e. https://github.com/nghorbani/human_body_prior/blob/SOMA/src/human_body_prior/tools/omni_tools.py
