### ISSUE TITLE
No body dataset

### ISSUE THREAD

**Issue by xueyang1823** [nghorbani/soma#5]
Thanks for your amazing work and it is very helpful to me. However, when I try Run SOMA on MoCap Point Cloud Data, I get some problems. Below are the error and the folder it mentions. Thanks a lot
![jupyter](https://user-images.githubusercontent.com/96585927/159435691-3078c4d3-31b5-42f7-825a-43e7166b3886.png)
![1](https://user-images.githubusercontent.com/96585927/159435714-2bf965de-78f3-4622-9542-775e6c8950c5.png)
.

**Comment by vigneshrk29** [comment]
Hi xueyang1823,

How did you fix this error? I am getting the same error

Thanks,
Vignesh

**Comment by xueyang1823** [comment]
Hi，
I delete the V48_02_SOMA folder and then run the code again. When you have this folder, the code that generates data won't work. Hope this can be helpful.

**Comment by vigneshrk29** [comment]
Thank you. That worked. Stuck in a different error now. Thanks

**Comment by whl-007** [comment]
> Thank you. That worked. Stuck in a different error now. Thanks

Did you find another error？I stuck in another error.
soma-main/src/soma/data/body_synthesizer.py in _betas_sampler(self, betas, single_beta_perseq)
    117     def _betas_sampler(self, betas, single_beta_perseq=True):
    118 
--> 119         logger.debug(f'Total beta parameters {len(betas):05d} ')
    120 
    121         def gen_betas(T):

TypeError: object of type 'NoneType' has no len()
