### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'distributed_backend'

### ISSUE THREAD

**Issue by karan00713** [nghorbani/soma#7]
When i tried to run soma on soma dataset using the given ipynb file in jupyter notebook, it gave me error      

train_multiple_soma(
    soma_data_settings=soma_data_settings,
    soma_train_cfg={
        'soma.expr_id': soma_expr_id, # the experiment ID

        'dirs.support_base_dir': support_base_dir,
        'dirs.work_base_dir': soma_work_base_dir,
        'data_parms.mocap_dataset.amass_marker_noise_model.enable': False, # we cannot create amass marker noise model
        
        'moshpp_cfg_override.moshpp.verbosity': 1,
        'moshpp_cfg_override.dirs.support_base_dir':support_base_dir,

        'trainer.fast_dev_run': False, # if true then only one iteration of training and validation is done.

        'data_parms.mocap_dataset.marker_layout_fnames': [soma_marker_layout_fname],
        'train_parms.batch_size': 256,
        'trainer.num_gpus': num_gpus,
        'train_parms.num_workers': num_cpus,
    },
)

***TypeError: __init__() got an unexpected keyword argument 'distributed_backend'***

*My specification : 
Ubuntu 20.04
python 3.7
pytorch version 1.5.10*

**Comment by Neil0511** [comment]
I also got the same error. It seems 'distributed_backend' has been depreicated in newer pytorch versions. This worked for me so maybe you can try the same. Replace 'distributed_backend' with 'strategy' in conf file i.e, "soma_train_conf.yaml". Also, change the same in trainer object in soma_trainer.py
