### ISSUE TITLE
UnsupportedInterpolationType: Unsupported interpolation type resolve_mocap_subject

### ISSUE THREAD

**Issue by Neil0511** [nghorbani/soma#8]
When trying to run "Running SOMA On MoCap Point Cloud Data" by following the steps in tutorial 1, getting this error: 

**UnsupportedInterpolationType:** Unsupported interpolation type resolve_mocap_subject
    full_key: dirs.mocap_out_fname
    object_type=dict
    
Also, I tried to change the variable 'soma_mocap_target_ds_name' to 'SOMA_unlabeled_mpc/soma_subject1' as the .c3d files are in this folder. It removes the error but output says zero jobs submitted.

2022-04-11 13:02:22.358 | INFO     | soma.tools.run_soma_multiple:run_soma_on_multiple_settings:245 - Submitting SOMA jobs.
2022-04-11 13:02:22.366 | INFO     | soma.tools.parallel_tools:run_parallel_jobs:54 - #Job(s) submitted: 0
2022-04-11 13:02:22.366 | INFO     | soma.tools.parallel_tools:run_parallel_jobs:67 - Will run the jobs in random order.

Any help would be really appreciated. Thanks in advance!

**Comment by vigneshrk29** [comment]
Hello,

Did you manage to resolve this error? I am facing the same error

Thanks,
Vignesh

**Comment by Neil0511** [comment]
No, haven't resolved this issue yet :(

**Comment by vigneshrk29** [comment]
Ya, and a similar error occurs at all instances of run soma on multiple settings. A similar error also occured in run mosh manual in the 4th tutorial

**Comment by karan00713** [comment]
@Neil0511 @vigneshrk29 still facing that issue? I'm too facing that issue now

**Comment by Neil0511** [comment]
There seemed to be some missing or invalid parameters in "soma_run_conf.yaml", I changed the strings for filenames and directories which worked for me

**Comment by karan00713** [comment]
Hey @Neil0511 , Could you tell more clear like which filenames and directories i have to rename ?

**Comment by vigneshrk29** [comment]
Hey, thanks will try it. Did you manage to get it to display using amass script as stated in the last part of the tutorial?

**Comment by zhaoyaxin-bytedance** [comment]
> There seemed to be some missing or invalid parameters in "soma_run_conf.yaml", I changed the strings for filenames and directories which worked for me

Hello, what do I need to modify in the yaml file? Looking forward to your reply

**Comment by minushuang** [comment]
it maybe a typo i think, and you can just modify the line4 in `soma_run_conf.yaml` 
from 
`subject_name: ${resolve_mocap_subject:${mocap.fname}}`
to
`subject_name: ${resolve_mocap_subjects:${mocap.fname}}`

**Comment by aric0103** [comment]
> it maybe a typo i think, and you can just modify the line4 in `soma_run_conf.yaml` from `subject_name: ${resolve_mocap_subject:${mocap.fname}}` to `subject_name: ${resolve_mocap_subjects:${mocap.fname}}`

Hi, I have modified the soma conf yaml file, but I got the subjects name "Null", did you have the same problem?

**Comment by naruya** [comment]
> Hi, I have modified the soma conf yaml file, but I got the subjects name "Null", did you have the same problem?

Same problem for me. Labeled mocap data (by `run_tasks=['soma']`, in `tutorials/run_soma_on_soma_dataset.ipynb`) is saved in the following location.

`/root/workspace/soma/training_experiments/V48_02_SOMA/OC_05_G_03_real_000_synt_100/evaluations/soma_labeled_mocap_tracklet/SOMA_unlabeled_mpc/['null']/squat_001.pkl`

I'll look into the cause.

**Comment by ritaank** [comment]
@naruya did you find the cause point?

**Comment by naruya** [comment]
(Sorry for not updating…)

Yes, I have found the cause and the error has been resolved in my env.

First of all, I think this solution above is wrong.
https://github.com/nghorbani/soma/issues/8#issuecomment-1158792010 ↓

> it maybe a typo i think, and you can just modify the line4 in soma_run_conf.yaml
> from
> subject_name: ${resolve_mocap_subject:${mocap.fname}}
> to
> subject_name: ${resolve_mocap_subjects:${mocap.fname}}


Looking at this commit, you can see that `resolve_mocap_subject` has been renamed to `resolve_mocap_session`.
https://github.com/nghorbani/moshpp/commit/8d2367e4077a906bce9d973bdb7d76ece89cff68#diff-0807837837e12683bd93beb828edeaa36f3f662118294da99ea3a26cf91db4b6L102-R148

```diff
-     if not OmegaConf.has_resolver('resolve_mocap_subject'):
-         OmegaConf.register_new_resolver('resolve_mocap_subject',
+     if not OmegaConf.has_resolver('resolve_mocap_session'):
+         OmegaConf.register_new_resolver('resolve_mocap_session',
```

So, if you rewrite `resolve_mocap_subject` in `soma/support_data/conf/eval_label.yaml` or `soma/support_data/conf/eval_v2v.yaml` to `resolve_mocap_session`, the error will be gone. And I successfully ran the tutorial on "the Solving SOMA MoCap Dataset".

(Notes, I followed the README very very faithfully.)

Actually, I think the best solution is to match the moshpp version with the soma version properly, but I haven't investigated that far.

(... my notes from a month ago say like above...)

@ritaank

**Comment by whl-007** [comment]
> (Sorry for not updating…)
> 
> Yes, I have found the cause and the error has been resolved in my env.
> 
> First of all, I think this solution above is wrong. [#8 (comment)](https://github.com/nghorbani/soma/issues/8#issuecomment-1158792010) ↓
> 
> > it maybe a typo i think, and you can just modify the line4 in soma_run_conf.yaml
> > from
> > subject_name: ${resolve_mocap_subject:${mocap.fname}}
> > to
> > subject_name: ${resolve_mocap_subjects:${mocap.fname}}
> 
> Looking at this commit, you can see that `resolve_mocap_subject` has been renamed to `resolve_mocap_session`. [nghorbani/moshpp@8d2367e#diff-0807837837e12683bd93beb828edeaa36f3f662118294da99ea3a26cf91db4b6L102-R148](https://github.com/nghorbani/moshpp/commit/8d2367e4077a906bce9d973bdb7d76ece89cff68#diff-0807837837e12683bd93beb828edeaa36f3f662118294da99ea3a26cf91db4b6L102-R148)
> 
> ```diff
> -     if not OmegaConf.has_resolver('resolve_mocap_subject'):
> -         OmegaConf.register_new_resolver('resolve_mocap_subject',
> +     if not OmegaConf.has_resolver('resolve_mocap_session'):
> +         OmegaConf.register_new_resolver('resolve_mocap_session',
> ```
> 
> So, if you rewrite `resolve_mocap_subject` in `soma/support_data/conf/eval_label.yaml` or `soma/support_data/conf/eval_v2v.yaml` to `resolve_mocap_session`, the error will be gone. And I successfully ran the tutorial on "the Solving SOMA MoCap Dataset".
> 
> (Notes, I followed the README very very faithfully.)
> 
> Actually, I think the best solution is to match the moshpp version with the soma version properly, but I haven't investigated that far.
> 
> (... my notes from a month ago say like above...)
> 
> @ritaank

I don't know if I tried your operation, but still gave me the following error. If you could help me answer it, I would greatly appreciate it!
![image](https://github.com/nghorbani/soma/assets/120098257/b0a1c749-deb0-4629-9604-bb5bc5267ce5)
